import imgOne from "./screenshots/KD.png";
import imgTwo from "./screenshots/Majun.png";

export default {
  "1": {
    name: "KD-128-8",
    date: "Mar 2020",
    sampleRate: 30000,
    duration: 1600,
    status: "spikesorted",
    rawView: imgOne,
  },
  "2": {
    name: "AP-64-8",
    date: "Apr 2020",
    sampleRate: 30000,
    duration: 2400,
    status: "spikesorting in progress..",
    rawView: imgOne,
  },
  "3": {
    name: "Wu-uLED-32",
    date: "Dec 2014",
    sampleRate: 30000,
    duration: 36000,
    status: "spikesorting in progress..",
    rawView: imgOne,
  },
  "4": {
    name: "ES-128-8",
    date: "Jun 2020",
    sampleRate: 30000,
    duration: 36000,
    status: "not spikesorted",
    rawView: imgTwo,
  },
  "5": {
    name: "MJ-tetrode-4",
    date: "May 2017",
    sampleRate: 1250,
    duration: 4000,
    status: "LFP only",
    rawView: imgTwo,
  },
  "6": {
    name: "MJ-tetrode-5",
    date: "May 2017",
    sampleRate: 1250,
    duration: 6000,
    status: "LFP only",
    rawView: imgTwo,
  },
  "7": {
    name: "MJ-tetrode-6",
    date: "May 2017",
    sampleRate: 1250,
    duration: 1000,
    status: "LFP only",
    rawView: imgTwo,
  },
  "8": {
    name: "MJ-tetrode-7",
    date: "May 2017",
    sampleRate: 1250,
    duration: 1000,
    status: "LFP only",
    rawView: imgTwo,
  },
  "9": {
    name: "MJ-tetrode-8",
    date: "May 2017",
    sampleRate: 1250,
    duration: 1000,
    status: "LFP only",
    rawView: imgTwo,
  },
};
